---
# tasks file for node-exporter
- name: Download and install node_exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-armv6.tar.gz"
    dest: /usr/local/bin
    remote_src: yes
    extra_opts: [--strip-components=1]
- name: Create {{ node_exporter_user }} user
  user:
    name: "{{ node_exporter_user }}"
    system: yes
    shell: /sbin/nologin
    state: present
- name: Copy node_exporter service file to systemd
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
- name: Ensure node_exporter dir exists
  file: 
    path: /etc/node_exporter
    state: directory
- name: Template node_exporter config file
  template:
    src: sysconfig.node_exporter.j2
    dest: /etc/node_exporter/node_exporter
    owner: root
    group: root
    mode: 0644
- name: Reload systemd
    systemd:
      daemon_reload: yes
- name: Enable node_exporter
    systemd:
      name: node_exporter
      enabled: yes
    notify: restart node_exporter