---
# tasks file for observer-web
- name: Copy nginx conf file to system
  template:
    src: nginx.conf.j2
    dest: "{{ observer_configdir }}/nginx.conf"
    owner: "{{ observer_user }}"
    group: "{{ observer_user }}"
    mode: 0755
- name: Copy web env file to system
  template:
    src: web.env.j2
    dest: "{{ observer_configdir }}/web.env"
    owner: "{{ observer_user }}"
    group: "{{ observer_user }}"
    mode: 0755
- name: Login to Docker Hub
  docker_login:
    username: "{{ observer_dockerhub_user }}"
    password: "{{ observer_dockerhub_pw }}"
    reauthorize: yes
  become: true
  become_user: "{{ observer_user }}"
- name: Create observer web container
  docker_container:
    name: observer_web
    image: joshdmoore/aspen-app:{{ observer_web_version }}
    env_file: "{{ observer_configdir }}/web.env"
    restart_policy: always
    network_mode: host
    volumes:
      - "{{ observer_configdir }}/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "{{ observer_rundir }}/observer.sock:{{ observer_rundir }}/observer.sock"
  become: true
  become_user: "{{ observer_user }}"